title: The Pel Code 
author: Celestia Harpster
email: Celestia.harpster@colo.state.edu
description: > # this means to ignore newlines until "baseurl:"
  Learning how to be a coder, here to get some knowledge. 

# social links
github_username:  PelHarp # DO NOT include the @ character, or else the build will fail!
tumblr_username: dumpthisthought

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
